Fixed cacheSolve to use solve instead of mean
#EG
> source('cachematrix.R')
> cacheTree <- makeCacheMatrix(tree)
> cacheTree$get()
     [,1] [,2] [,3]
[1,]    2    1    0
[2,]    2    0    0
[3,]    2    0    1
> cacheTree$getmean()
NULL
> cacheTree$getinverse()
NULL
> cacheSolve(cacheTree)
     [,1] [,2] [,3]
[1,]    0  0.5    0
[2,]    1 -1.0    0
[3,]    0 -1.0    1
> cacheTree$getmean()
NULL
> cacheTree$getinverse()
     [,1] [,2] [,3]
[1,]    0  0.5    0
[2,]    1 -1.0    0
[3,]    0 -1.0    1
> chacheMean(cacheTree)
Error: could not find function "chacheMean"
> cacheMean(cacheTree)
[1] 0.8888889
> cacheTree$getmean()
[1] 0.8888889
> cacheTree$getinverse()
     [,1] [,2] [,3]
[1,]    0  0.5    0
[2,]    1 -1.0    0
[3,]    0 -1.0    1
>